### PR TITLE
MNT: try to get bdist_wheel class from setuptools not wheel

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by hynek** [comment]
shouldn't this be against main, too?

**Comment by tacaswell** [comment]
Yes, but I had it on top of the nogil branch.  I can cherry-pick it to be against main if you prefer.

**Comment by hynek** [comment]
yeah please do; who knows how long it'll take until the nogil branch goes anywhere…

**Comment by hynek** [comment]
never mind, I'll do it myself :) thanks!

**Pull request merged**
