### PR TITLE
Add 3.13 to CI

### PR DESCRIPTION
**Pull request by hynek**
We'll need a CFFI release first, though.

ref https://github.com/hynek/argon2-cffi/pull/175

### CODE REVIEW

**Comment by hynek** [comment]
I do not plan on releasing as it is right now until we got a public 1.17.

**Comment by minrk** [comment]
FWIW, free-threaded CPython 3.13 [doesn't support the limited API](https://docs.python.org/3.13/howto/free-threading-extensions.html#limited-c-api-and-stable-abi), so to you'll need to set `py_limited_api=False` when `sysconfig.get_config_var("Py_GIL_DISABLED")`, both in setup.py and ffi.set_source, I believe, in order to get this package to install for cp313t builds.

CFFI doesn't officially support free-threaded Python yet, so perhaps not much reason to pursue it now. That said, I've successfully installed argon2-cffi with

- e9eb1363083bae82d30ddbe1a8f38237d66b99a6 on this repo, and
- https://github.com/python-cffi/cffi/pull/106

 and all tests argon2-cffi pass and Jupyter things run (arm64 mac). That isn't likely to exercise potential threadsafety issues, though.

**Comment by hynek** [comment]
In principle, CFFI always release the GIL , so I hope that it’s gonna be just a matter of compilation flags. 😬

**Comment by tacaswell** [comment]
I also needed https://github.com/python-cffi/cffi/pull/112

**Pull request merged**
